database:
  host: localhost
  port: 5432
  username: postgres
  password:
  schema: postgres
spring:
  application:
    name: menu
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${database.host}:${database.port}/${database.schema}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
